# Generated by Django 3.1.3 on 2020-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(db_table='albums_artists', to='albums.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(db_table='albums_songs', to='albums.Song'),
        ),
    ]
