# Generated by Django 3.1.3 on 2020-12-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumsPlayLink',
            new_name='AlbumPlayLink',
        ),
        migrations.RenameField(
            model_name='albumplaylink',
            old_name='albums',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albumplaylink',
            old_name='play_links',
            new_name='play_link',
        ),
    ]
