# Generated by Django 3.1.3 on 2020-12-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date_performance', models.DateTimeField()),
                ('post_url', models.URLField(max_length=256)),
                ('thumbnail_url', models.URLField(max_length=256)),
                ('info_detail', models.TextField()),
                ('date_ticketing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='TicketingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'ticketing_sites',
            },
        ),
        migrations.CreateModel(
            name='ConcertTicketingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=126)),
                ('concert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
                ('ticketing_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.ticketingsite')),
            ],
            options={
                'db_table': 'concert_ticketingsite',
            },
        ),
        migrations.CreateModel(
            name='ConcertSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('concert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.seat')),
            ],
            options={
                'db_table': 'concerts_seats',
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='host',
            field=models.ManyToManyField(to='concerts.Host'),
        ),
        migrations.AddField(
            model_name='concert',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.location'),
        ),
        migrations.AddField(
            model_name='concert',
            name='seat',
            field=models.ManyToManyField(through='concerts.ConcertSeat', to='concerts.Seat'),
        ),
        migrations.AddField(
            model_name='concert',
            name='ticketing_site',
            field=models.ManyToManyField(blank=True, through='concerts.ConcertTicketingSite', to='concerts.TicketingSite'),
        ),
    ]
