# Generated by Django 3.1.3 on 2020-12-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concert',
            table='concerts',
        ),
    ]
