# Generated by Django 3.1.3 on 2020-12-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20201215_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concertticketingsite',
            table='concerts_ticketing_sites',
        ),
    ]
