# Generated by Django 3.1.3 on 2020-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_auto_20201215_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='host',
            field=models.ManyToManyField(to='concerts.Host', verbose_name='hosts'),
        ),
    ]
